
trigger:
  branches:
    include:
      - main

pr:
  branches:
    include:
      - main

variables:
  nodeVersion: '20.x'
  artifactName: 'angular-starter'
  distFolder: 'dist'

  # Azure service connection
  azureSubscription: ''

  # App Services per environment
  devAppName: 'angular-starter-dev'
  testAppName: 'angular-starter-test'
  prodAppName: 'angular-starter-prod'

stages:

# =====================================================
# CI STAGE – Build & Test Once
# =====================================================
- stage: CI
  displayName: 'CI - Build & Test'
  jobs:
  - job: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:

    - task: NodeTool@0
      inputs:
        versionSpec: '$(nodeVersion)'
      displayName: 'Install Node.js'

    - script: npm ci
      displayName: 'Install dependencies'

    - script: npm run test --if-present
      displayName: 'Run unit tests (Jest)'

    # Build with PROD config (safe default for promotion)
    - script: npm run build -- --configuration production
      displayName: 'Build Angular app (prod)'

    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(distFolder)'
        artifactName: '$(artifactName)'
      displayName: 'Publish build artifact'

